name: DemonlyFactions
main: xyz.FactionsD.FactionsD
version: 0.1
author: Demonly
softdepend: [PlaceholderAPI]
commands:
  faction:
    description: Open the Factions Menu
    aliases: [fac, factions, f, fa]
  developer:
    description: Faction Developer command